### ISSUE TITLE
Please Fix the MP3 WAV flv data format errors

### ISSUE THREAD

**Issue by lifeiteng** [CheyneyComputerScience/CREMA-D#3]
I cann't open those files
run `ffmpeg -i CREMA-D-master/AudioWAV/1001_DFA_ANG_XX.wav test.wav`
got `CREMA-D-master/AudioWAV/1001_DFA_ANG_XX.wav: Invalid data found when processing input`

**Comment by DavidCooperWCU** [comment]
Hi, Feiteng,

Based on your description, it looks like you downloaded the zip file of the repository or you cloned the repository without using git-lfs. The repository uses git-lfs for all of the media files, so the zip file just has links in place of the mp3 and wav files. In order to get the whole repository, you need to install git and git-lfs on your computer and then clone the repository.

To verify that this is the problem try the following:
`cat CREMA-D-master/AudioWAV/1001_DFA_ANG_XX.wav`

You should get:
```
version https://git-lfs.github.com/spec/v1
oid sha256:c6f94b2592487c7556bd86df7df6e8f4420d1b9c11414aeec9d8e5e640b51495
size 72862
```

If this is not what you get, please do reopen this issue, and post what is happening.
