### ISSUE TITLE
Incorrectly named file

### ISSUE THREAD

**Issue by tanishqvyas** [CheyneyComputerScience/CREMA-D#6]
The file present inside ```AudioWAV``` folder is incorrectly named as ```1040_ITH_SAD_X.wav```. It must be named ```1040_ITH_SAD_XX.wav``` as per the directions given in the README.md file.

**Comment by Coding511** [comment]
@tanishqvyas Can you read these audio and video files?

**Comment by tanishqvyas** [comment]
@Coding511 Yes, I am able to read these files. These are actually pointers to file so you may need to use `git-lfs`

**Comment by Coding511** [comment]
@tanishqvyas Could you please explain it, I am new here on Github
I have downloaded the code to my local machine, Then opened these wave files as well video, but none is working.

**Comment by Coding511** [comment]
Or it's best if you can upload it here or send us as the file size is not huge. If you are okay with this plz.

codingpython511@gmail.com

**Comment by DavidCooperWCU** [comment]
@tanishqvyas - Thanks for noticing this. I have updated the file to have the correct name and still link to the same git-lfs file. (Hopefully the git-lfs file will remain, since I deleted the file with only X after adding the one with XX.

@Coding511 please read the Readme that explains how to use git-lfs, otherwise, if you download the files with GitHub Desktop, then that has git-lfs built in now so it should download all of the git-lfs links for you.
